package com.hilary.lexer;

public enum TokenType {
    KEYWORD, IDENTIFIER,
    INT_LITERAL, FLOAT_LITERAL, STRING_LITERAL,
    ASSIGN, EQ, NE, LT, LE, GT, GE, PLUS, MINUS, MUL, DIV, MOD, AND, OR, NOT,
    COMMA, SEMI, LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    ERROR
}
